# Generated by Django 5.1.4 on 2024-12-14 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='description',
        ),
        migrations.AddField(
            model_name='comment',
            name='supplement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.supplement'),
        ),
        migrations.AddField(
            model_name='condition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='pages.condition'),
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplement',
            name='category',
            field=models.CharField(default='No Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
    ]
