# Generated by Django 5.1.4 on 2024-12-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_rating_unique_together_remove_comment_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='supplement',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='conditions',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pages.rating'),
        ),
    ]
