# Generated by Django 5.1.4 on 2025-01-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_merge_0002_brand_add_dosage_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='dosage_frequency',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='frequency_unit',
            field=models.CharField(blank=True, choices=[('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year')], default='day', max_length=10, null=True),
        ),
    ]
