# Generated by Django 5.1.4 on 2024-12-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_comment_parent_remove_comment_supplement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='description',
        ),
    ]
