# Generated by Django 5.1.4 on 2024-12-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_condition_description'),
    ]

    operations = [
    ]
