# Generated by Django 5.1.4 on 2025-01-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_rating_dosage_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
