# Generated by Django 5.1.4 on 2024-12-15 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20241215_1837'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.condition'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'supplement', 'condition')},
        ),
    ]
