# Generated by Django 5.1.4 on 2025-01-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_userupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ratings/'),
        ),
    ]
