# Generated by Django 5.1.4 on 2024-12-18 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_comment_rating_alter_condition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rating',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pages.condition'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pages.supplement'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='category',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
