# Generated by Django 5.1.4 on 2024-12-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_comment_content_alter_rating_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='review',
            name='supplement',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
