# Generated by Django 5.1.4 on 2024-12-18 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_review_condition_remove_review_supplement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pages.condition'),
        ),
    ]
