# Generated by Django 4.2.19 on 2025-05-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chronic_conditions',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='pages.condition'),
        ),
    ]
