# Generated by Django 4.2.19 on 2025-05-25 14:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0010_profile_chronic_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='benefits',
            field=models.ManyToManyField(blank=True, related_name='benefit_ratings', to='pages.condition'),
        ),
        migrations.AddField(
            model_name='rating',
            name='side_effects',
            field=models.ManyToManyField(blank=True, related_name='side_effect_ratings', to='pages.condition'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='conditions',
            field=models.ManyToManyField(related_name='condition_ratings', to='pages.condition'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
