# Generated by Django 5.1.4 on 2024-12-23 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'supplement')},
        ),
        migrations.AddField(
            model_name='rating',
            name='conditions',
            field=models.ManyToManyField(related_name='ratings', to='pages.condition'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='condition',
        ),
    ]
