# Generated by Django 5.2 on 2025-08-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rating_benefits_rating_side_effects_and_more'),
        ('pages', '0015_profile_image_default_fix'),
    ]

    operations = [
    ]
